"""Aggregated Instagram exception failure specifications."""

from .common_client import (
    SPEC_CLIENT_ERROR,
    SPEC_GENERIC_REQUEST_ERROR,
    SPEC_CLIENT_GRAPHQL_ERROR,
    SPEC_CLIENT_JSON_DECODE_ERROR,
    SPEC_CLIENT_CONNECTION_ERROR,
    SPEC_CLIENT_BAD_REQUEST_ERROR,
    SPEC_CLIENT_UNAUTHORIZED_ERROR,
    SPEC_CLIENT_FORBIDDEN_ERROR,
    SPEC_CLIENT_NOT_FOUND_ERROR,
    SPEC_CLIENT_THROTTLED_ERROR,
    SPEC_CLIENT_REQUEST_TIMEOUT,
    SPEC_CLIENT_INCOMPLETE_READ_ERROR,
    SPEC_CLIENT_LOGIN_REQUIRED,
    SPEC_RELOGIN_ATTEMPT_EXCEEDED,
    SPEC_CLIENT_ERROR_WITH_TITLE,
    SPEC_CLIENT_UNKNOWN_ERROR,
    SPEC_WRONG_CURSOR_ERROR,
    SPEC_CLIENT_STATUS_FAIL,
)

from .proxy import (
    SPEC_PROXY_ERROR,
    SPEC_CONNECT_PROXY_ERROR,
    SPEC_AUTH_REQUIRED_PROXY_ERROR,
    SPEC_PROXY_ADDRESS_IS_BLOCKED,
    SPEC_SENTRY_BLOCK,
    SPEC_RATE_LIMIT_ERROR,
    SPEC_PLEASE_WAIT_FEW_MINUTES,
)

from .private_auth import (
    SPEC_PRIVATE_ERROR,
    SPEC_FEEDBACK_REQUIRED,
    SPEC_PRE_LOGIN_REQUIRED,
    SPEC_BAD_PASSWORD,
    SPEC_TWO_FACTOR_REQUIRED,
    SPEC_BAD_CREDENTIALS,
    SPEC_IS_REGULATED_C18_ERROR,
)

from .challenge import (
    SPEC_CHALLENGE_ERROR,
    SPEC_CHALLENGE_REDIRECTION,
    SPEC_CHALLENGE_REQUIRED,
    SPEC_CHALLENGE_SELFIE_CAPTCHA,
    SPEC_CHALLENGE_UNKNOWN_STEP,
    SPEC_SELECT_CONTACT_POINT_RECOVERY_FORM,
    SPEC_RECAPTCHA_CHALLENGE_FORM,
    SPEC_SUBMIT_PHONE_NUMBER_FORM,
    SPEC_LEGACY_FORCE_SET_NEW_PASSWORD_FORM,
    SPEC_CONSENT_REQUIRED,
    SPEC_GEO_BLOCK_REQUIRED,
    SPEC_CHECKPOINT_REQUIRED,
)

from .media import (
    SPEC_MEDIA_ERROR,
    SPEC_MEDIA_NOT_FOUND,
    SPEC_INVALID_TARGET_USER,
    SPEC_INVALID_MEDIA_ID,
    SPEC_MEDIA_UNAVAILABLE,
)

from .user import (
    SPEC_USER_ERROR,
    SPEC_USER_NOT_FOUND,
    SPEC_PRIVATE_ACCOUNT,
)

from .account import (
    SPEC_ACCOUNT_SUSPENDED,
    SPEC_TERMS_UNBLOCK,
    SPEC_TERMS_ACCEPT,
    SPEC_ABOUT_US_ERROR,
    SPEC_RESET_PASSWORD_ERROR,
    SPEC_UNSUPPORTED_ERROR,
    SPEC_UNSUPPORTED_SETTING_VALUE,
)

from .collection import (
    SPEC_COLLECTION_ERROR,
    SPEC_COLLECTION_NOT_FOUND,
)

from .direct import (
    SPEC_DIRECT_ERROR,
    SPEC_DIRECT_THREAD_NOT_FOUND,
    SPEC_DIRECT_MESSAGE_NOT_FOUND,
)

from .photo import (
    SPEC_PHOTO_NOT_DOWNLOAD,
    SPEC_PHOTO_NOT_UPLOAD,
    SPEC_PHOTO_CONFIGURE_ERROR,
    SPEC_PHOTO_CONFIGURE_STORY_ERROR,
)

from .video import (
    SPEC_VIDEO_NOT_DOWNLOAD,
    SPEC_VIDEO_NOT_UPLOAD,
    SPEC_VIDEO_CONFIGURE_ERROR,
    SPEC_VIDEO_CONFIGURE_STORY_ERROR,
    SPEC_VIDEO_TOO_LONG_EXCEPTION,
)

from .igtv import (
    SPEC_IGTV_NOT_UPLOAD,
    SPEC_IGTV_CONFIGURE_ERROR,
)

from .clip import (
    SPEC_CLIP_NOT_UPLOAD,
    SPEC_CLIP_CONFIGURE_ERROR,
)

from .album import (
    SPEC_ALBUM_NOT_DOWNLOAD,
    SPEC_ALBUM_UNKNOWN_FORMAT,
    SPEC_ALBUM_CONFIGURE_ERROR,
)

from .story import (
    SPEC_STORY_NOT_FOUND,
)

from .highlight import (
    SPEC_HIGHLIGHT_NOT_FOUND,
)

from .hashtag import (
    SPEC_HASHTAG_ERROR,
    SPEC_HASHTAG_NOT_FOUND,
    SPEC_HASHTAG_PAGE_WARNING,
)

from .location import (
    SPEC_LOCATION_ERROR,
    SPEC_LOCATION_NOT_FOUND,
)

from .comment import (
    SPEC_COMMENT_NOT_FOUND,
    SPEC_COMMENTS_DISABLED,
)

from .share import (
    SPEC_SHARE_DECODE_ERROR,
)

from .note import (
    SPEC_NOTE_NOT_FOUND,
)

from .track import (
    SPEC_TRACK_NOT_FOUND,
)


__all__ = [
    "SPEC_CLIENT_ERROR",
    "SPEC_GENERIC_REQUEST_ERROR",
    "SPEC_CLIENT_GRAPHQL_ERROR",
    "SPEC_CLIENT_JSON_DECODE_ERROR",
    "SPEC_CLIENT_CONNECTION_ERROR",
    "SPEC_CLIENT_BAD_REQUEST_ERROR",
    "SPEC_CLIENT_UNAUTHORIZED_ERROR",
    "SPEC_CLIENT_FORBIDDEN_ERROR",
    "SPEC_CLIENT_NOT_FOUND_ERROR",
    "SPEC_CLIENT_THROTTLED_ERROR",
    "SPEC_CLIENT_REQUEST_TIMEOUT",
    "SPEC_CLIENT_INCOMPLETE_READ_ERROR",
    "SPEC_CLIENT_LOGIN_REQUIRED",
    "SPEC_RELOGIN_ATTEMPT_EXCEEDED",
    "SPEC_CLIENT_ERROR_WITH_TITLE",
    "SPEC_CLIENT_UNKNOWN_ERROR",
    "SPEC_WRONG_CURSOR_ERROR",
    "SPEC_CLIENT_STATUS_FAIL",
    "SPEC_PROXY_ERROR",
    "SPEC_CONNECT_PROXY_ERROR",
    "SPEC_AUTH_REQUIRED_PROXY_ERROR",
    "SPEC_PROXY_ADDRESS_IS_BLOCKED",
    "SPEC_SENTRY_BLOCK",
    "SPEC_RATE_LIMIT_ERROR",
    "SPEC_PLEASE_WAIT_FEW_MINUTES",
    "SPEC_PRIVATE_ERROR",
    "SPEC_FEEDBACK_REQUIRED",
    "SPEC_PRE_LOGIN_REQUIRED",
    "SPEC_BAD_PASSWORD",
    "SPEC_TWO_FACTOR_REQUIRED",
    "SPEC_BAD_CREDENTIALS",
    "SPEC_IS_REGULATED_C18_ERROR",
    "SPEC_CHALLENGE_ERROR",
    "SPEC_CHALLENGE_REDIRECTION",
    "SPEC_CHALLENGE_REQUIRED",
    "SPEC_CHALLENGE_SELFIE_CAPTCHA",
    "SPEC_CHALLENGE_UNKNOWN_STEP",
    "SPEC_SELECT_CONTACT_POINT_RECOVERY_FORM",
    "SPEC_RECAPTCHA_CHALLENGE_FORM",
    "SPEC_SUBMIT_PHONE_NUMBER_FORM",
    "SPEC_LEGACY_FORCE_SET_NEW_PASSWORD_FORM",
    "SPEC_CONSENT_REQUIRED",
    "SPEC_GEO_BLOCK_REQUIRED",
    "SPEC_CHECKPOINT_REQUIRED",
    "SPEC_MEDIA_ERROR",
    "SPEC_MEDIA_NOT_FOUND",
    "SPEC_INVALID_TARGET_USER",
    "SPEC_INVALID_MEDIA_ID",
    "SPEC_MEDIA_UNAVAILABLE",
    "SPEC_USER_ERROR",
    "SPEC_USER_NOT_FOUND",
    "SPEC_PRIVATE_ACCOUNT",
    "SPEC_ACCOUNT_SUSPENDED",
    "SPEC_TERMS_UNBLOCK",
    "SPEC_TERMS_ACCEPT",
    "SPEC_ABOUT_US_ERROR",
    "SPEC_RESET_PASSWORD_ERROR",
    "SPEC_UNSUPPORTED_ERROR",
    "SPEC_UNSUPPORTED_SETTING_VALUE",
    "SPEC_COLLECTION_ERROR",
    "SPEC_COLLECTION_NOT_FOUND",
    "SPEC_DIRECT_ERROR",
    "SPEC_DIRECT_THREAD_NOT_FOUND",
    "SPEC_DIRECT_MESSAGE_NOT_FOUND",
    "SPEC_PHOTO_NOT_DOWNLOAD",
    "SPEC_PHOTO_NOT_UPLOAD",
    "SPEC_PHOTO_CONFIGURE_ERROR",
    "SPEC_PHOTO_CONFIGURE_STORY_ERROR",
    "SPEC_VIDEO_NOT_DOWNLOAD",
    "SPEC_VIDEO_NOT_UPLOAD",
    "SPEC_VIDEO_CONFIGURE_ERROR",
    "SPEC_VIDEO_CONFIGURE_STORY_ERROR",
    "SPEC_VIDEO_TOO_LONG_EXCEPTION",
    "SPEC_IGTV_NOT_UPLOAD",
    "SPEC_IGTV_CONFIGURE_ERROR",
    "SPEC_CLIP_NOT_UPLOAD",
    "SPEC_CLIP_CONFIGURE_ERROR",
    "SPEC_ALBUM_NOT_DOWNLOAD",
    "SPEC_ALBUM_UNKNOWN_FORMAT",
    "SPEC_ALBUM_CONFIGURE_ERROR",
    "SPEC_STORY_NOT_FOUND",
    "SPEC_HIGHLIGHT_NOT_FOUND",
    "SPEC_HASHTAG_ERROR",
    "SPEC_HASHTAG_NOT_FOUND",
    "SPEC_HASHTAG_PAGE_WARNING",
    "SPEC_LOCATION_ERROR",
    "SPEC_LOCATION_NOT_FOUND",
    "SPEC_COMMENT_NOT_FOUND",
    "SPEC_COMMENTS_DISABLED",
    "SPEC_SHARE_DECODE_ERROR",
    "SPEC_NOTE_NOT_FOUND",
    "SPEC_TRACK_NOT_FOUND",
]
