"""Registry wiring for instagrapi exception-to-failure mappings."""

from app.adapters.instagram.exception_catalog.model import FailureSpec
from app.adapters.instagram.exception_catalog.specs import (
    SPEC_CLIENT_ERROR,
    SPEC_GENERIC_REQUEST_ERROR,
    SPEC_CLIENT_GRAPHQL_ERROR,
    SPEC_CLIENT_JSON_DECODE_ERROR,
    SPEC_CLIENT_CONNECTION_ERROR,
    SPEC_CLIENT_BAD_REQUEST_ERROR,
    SPEC_CLIENT_UNAUTHORIZED_ERROR,
    SPEC_CLIENT_FORBIDDEN_ERROR,
    SPEC_CLIENT_NOT_FOUND_ERROR,
    SPEC_CLIENT_THROTTLED_ERROR,
    SPEC_CLIENT_REQUEST_TIMEOUT,
    SPEC_CLIENT_INCOMPLETE_READ_ERROR,
    SPEC_CLIENT_LOGIN_REQUIRED,
    SPEC_RELOGIN_ATTEMPT_EXCEEDED,
    SPEC_CLIENT_ERROR_WITH_TITLE,
    SPEC_CLIENT_UNKNOWN_ERROR,
    SPEC_WRONG_CURSOR_ERROR,
    SPEC_CLIENT_STATUS_FAIL,
    SPEC_PROXY_ERROR,
    SPEC_CONNECT_PROXY_ERROR,
    SPEC_AUTH_REQUIRED_PROXY_ERROR,
    SPEC_PROXY_ADDRESS_IS_BLOCKED,
    SPEC_SENTRY_BLOCK,
    SPEC_RATE_LIMIT_ERROR,
    SPEC_PLEASE_WAIT_FEW_MINUTES,
    SPEC_PRIVATE_ERROR,
    SPEC_FEEDBACK_REQUIRED,
    SPEC_PRE_LOGIN_REQUIRED,
    SPEC_BAD_PASSWORD,
    SPEC_TWO_FACTOR_REQUIRED,
    SPEC_BAD_CREDENTIALS,
    SPEC_IS_REGULATED_C18_ERROR,
    SPEC_CHALLENGE_ERROR,
    SPEC_CHALLENGE_REDIRECTION,
    SPEC_CHALLENGE_REQUIRED,
    SPEC_CHALLENGE_SELFIE_CAPTCHA,
    SPEC_CHALLENGE_UNKNOWN_STEP,
    SPEC_SELECT_CONTACT_POINT_RECOVERY_FORM,
    SPEC_RECAPTCHA_CHALLENGE_FORM,
    SPEC_SUBMIT_PHONE_NUMBER_FORM,
    SPEC_LEGACY_FORCE_SET_NEW_PASSWORD_FORM,
    SPEC_CONSENT_REQUIRED,
    SPEC_GEO_BLOCK_REQUIRED,
    SPEC_CHECKPOINT_REQUIRED,
    SPEC_MEDIA_ERROR,
    SPEC_MEDIA_NOT_FOUND,
    SPEC_INVALID_TARGET_USER,
    SPEC_INVALID_MEDIA_ID,
    SPEC_MEDIA_UNAVAILABLE,
    SPEC_USER_ERROR,
    SPEC_USER_NOT_FOUND,
    SPEC_PRIVATE_ACCOUNT,
    SPEC_ACCOUNT_SUSPENDED,
    SPEC_TERMS_UNBLOCK,
    SPEC_TERMS_ACCEPT,
    SPEC_ABOUT_US_ERROR,
    SPEC_RESET_PASSWORD_ERROR,
    SPEC_UNSUPPORTED_ERROR,
    SPEC_UNSUPPORTED_SETTING_VALUE,
    SPEC_COLLECTION_ERROR,
    SPEC_COLLECTION_NOT_FOUND,
    SPEC_DIRECT_ERROR,
    SPEC_DIRECT_THREAD_NOT_FOUND,
    SPEC_DIRECT_MESSAGE_NOT_FOUND,
    SPEC_PHOTO_NOT_DOWNLOAD,
    SPEC_PHOTO_NOT_UPLOAD,
    SPEC_PHOTO_CONFIGURE_ERROR,
    SPEC_PHOTO_CONFIGURE_STORY_ERROR,
    SPEC_VIDEO_NOT_DOWNLOAD,
    SPEC_VIDEO_NOT_UPLOAD,
    SPEC_VIDEO_CONFIGURE_ERROR,
    SPEC_VIDEO_CONFIGURE_STORY_ERROR,
    SPEC_VIDEO_TOO_LONG_EXCEPTION,
    SPEC_IGTV_NOT_UPLOAD,
    SPEC_IGTV_CONFIGURE_ERROR,
    SPEC_CLIP_NOT_UPLOAD,
    SPEC_CLIP_CONFIGURE_ERROR,
    SPEC_ALBUM_NOT_DOWNLOAD,
    SPEC_ALBUM_UNKNOWN_FORMAT,
    SPEC_ALBUM_CONFIGURE_ERROR,
    SPEC_STORY_NOT_FOUND,
    SPEC_HIGHLIGHT_NOT_FOUND,
    SPEC_HASHTAG_ERROR,
    SPEC_HASHTAG_NOT_FOUND,
    SPEC_HASHTAG_PAGE_WARNING,
    SPEC_LOCATION_ERROR,
    SPEC_LOCATION_NOT_FOUND,
    SPEC_COMMENT_NOT_FOUND,
    SPEC_COMMENTS_DISABLED,
    SPEC_SHARE_DECODE_ERROR,
    SPEC_NOTE_NOT_FOUND,
    SPEC_TRACK_NOT_FOUND,
)


EXCEPTION_REGISTRY: dict[type[Exception], FailureSpec] = {}
"""Maps instagrapi exception types to application failure specifications."""
_REGISTERED_EXCEPTION_NAMES: set[str] = set()
"""Names explicitly registered in this module (independent of runtime imports)."""


def _register_exception(exception_class_name: str, spec: FailureSpec) -> None:
    """
    Dynamically register an exception mapping by importing the class.

    This defers instagrapi imports to allow graceful handling if instagrapi
    is not installed, and keeps the registry size manageable.
    """
    _REGISTERED_EXCEPTION_NAMES.add(exception_class_name)
    try:
        import instagrapi.exceptions as exceptions

        if hasattr(exceptions, exception_class_name):
            exc_class = getattr(exceptions, exception_class_name)
            EXCEPTION_REGISTRY[exc_class] = spec
    except (ImportError, AttributeError):
        pass


REGISTRATION_SPECS: tuple[tuple[str, FailureSpec], ...] = (
    ("ClientError", SPEC_CLIENT_ERROR),
    ("GenericRequestError", SPEC_GENERIC_REQUEST_ERROR),
    ("ClientGraphqlError", SPEC_CLIENT_GRAPHQL_ERROR),
    ("ClientJSONDecodeError", SPEC_CLIENT_JSON_DECODE_ERROR),
    ("ClientConnectionError", SPEC_CLIENT_CONNECTION_ERROR),
    ("ClientBadRequestError", SPEC_CLIENT_BAD_REQUEST_ERROR),
    ("ClientUnauthorizedError", SPEC_CLIENT_UNAUTHORIZED_ERROR),
    ("ClientForbiddenError", SPEC_CLIENT_FORBIDDEN_ERROR),
    ("ClientNotFoundError", SPEC_CLIENT_NOT_FOUND_ERROR),
    ("ClientThrottledError", SPEC_CLIENT_THROTTLED_ERROR),
    ("ClientRequestTimeout", SPEC_CLIENT_REQUEST_TIMEOUT),
    ("ClientIncompleteReadError", SPEC_CLIENT_INCOMPLETE_READ_ERROR),
    ("ClientLoginRequired", SPEC_CLIENT_LOGIN_REQUIRED),
    ("ReloginAttemptExceeded", SPEC_RELOGIN_ATTEMPT_EXCEEDED),
    ("ClientErrorWithTitle", SPEC_CLIENT_ERROR_WITH_TITLE),
    ("ClientUnknownError", SPEC_CLIENT_UNKNOWN_ERROR),
    ("WrongCursorError", SPEC_WRONG_CURSOR_ERROR),
    ("ClientStatusFail", SPEC_CLIENT_STATUS_FAIL),
    ("ProxyError", SPEC_PROXY_ERROR),
    ("ConnectProxyError", SPEC_CONNECT_PROXY_ERROR),
    ("AuthRequiredProxyError", SPEC_AUTH_REQUIRED_PROXY_ERROR),
    ("ProxyAddressIsBlocked", SPEC_PROXY_ADDRESS_IS_BLOCKED),
    ("SentryBlock", SPEC_SENTRY_BLOCK),
    ("RateLimitError", SPEC_RATE_LIMIT_ERROR),
    ("PleaseWaitFewMinutes", SPEC_PLEASE_WAIT_FEW_MINUTES),
    ("PrivateError", SPEC_PRIVATE_ERROR),
    ("FeedbackRequired", SPEC_FEEDBACK_REQUIRED),
    ("PreLoginRequired", SPEC_PRE_LOGIN_REQUIRED),
    ("LoginRequired", SPEC_CLIENT_LOGIN_REQUIRED),
    ("BadPassword", SPEC_BAD_PASSWORD),
    ("TwoFactorRequired", SPEC_TWO_FACTOR_REQUIRED),
    ("BadCredentials", SPEC_BAD_CREDENTIALS),
    ("IsRegulatedC18Error", SPEC_IS_REGULATED_C18_ERROR),
    ("UnknownError", SPEC_CLIENT_UNKNOWN_ERROR),
    ("ChallengeError", SPEC_CHALLENGE_ERROR),
    ("ChallengeRedirection", SPEC_CHALLENGE_REDIRECTION),
    ("ChallengeRequired", SPEC_CHALLENGE_REQUIRED),
    ("ChallengeSelfieCaptcha", SPEC_CHALLENGE_SELFIE_CAPTCHA),
    ("ChallengeUnknownStep", SPEC_CHALLENGE_UNKNOWN_STEP),
    ("SelectContactPointRecoveryForm", SPEC_SELECT_CONTACT_POINT_RECOVERY_FORM),
    ("RecaptchaChallengeForm", SPEC_RECAPTCHA_CHALLENGE_FORM),
    ("SubmitPhoneNumberForm", SPEC_SUBMIT_PHONE_NUMBER_FORM),
    ("LegacyForceSetNewPasswordForm", SPEC_LEGACY_FORCE_SET_NEW_PASSWORD_FORM),
    ("ConsentRequired", SPEC_CONSENT_REQUIRED),
    ("GeoBlockRequired", SPEC_GEO_BLOCK_REQUIRED),
    ("CheckpointRequired", SPEC_CHECKPOINT_REQUIRED),
    ("MediaError", SPEC_MEDIA_ERROR),
    ("MediaNotFound", SPEC_MEDIA_NOT_FOUND),
    ("InvalidTargetUser", SPEC_INVALID_TARGET_USER),
    ("InvalidMediaId", SPEC_INVALID_MEDIA_ID),
    ("MediaUnavailable", SPEC_MEDIA_UNAVAILABLE),
    ("UserError", SPEC_USER_ERROR),
    ("UserNotFound", SPEC_USER_NOT_FOUND),
    ("PrivateAccount", SPEC_PRIVATE_ACCOUNT),
    ("AccountSuspended", SPEC_ACCOUNT_SUSPENDED),
    ("TermsUnblock", SPEC_TERMS_UNBLOCK),
    ("TermsAccept", SPEC_TERMS_ACCEPT),
    ("AboutUsError", SPEC_ABOUT_US_ERROR),
    ("ResetPasswordError", SPEC_RESET_PASSWORD_ERROR),
    ("UnsupportedError", SPEC_UNSUPPORTED_ERROR),
    ("UnsupportedSettingValue", SPEC_UNSUPPORTED_SETTING_VALUE),
    ("CollectionError", SPEC_COLLECTION_ERROR),
    ("CollectionNotFound", SPEC_COLLECTION_NOT_FOUND),
    ("DirectError", SPEC_DIRECT_ERROR),
    ("DirectThreadNotFound", SPEC_DIRECT_THREAD_NOT_FOUND),
    ("DirectMessageNotFound", SPEC_DIRECT_MESSAGE_NOT_FOUND),
    ("PhotoNotDownload", SPEC_PHOTO_NOT_DOWNLOAD),
    ("PhotoNotUpload", SPEC_PHOTO_NOT_UPLOAD),
    ("PhotoConfigureError", SPEC_PHOTO_CONFIGURE_ERROR),
    ("PhotoConfigureStoryError", SPEC_PHOTO_CONFIGURE_STORY_ERROR),
    ("VideoNotDownload", SPEC_VIDEO_NOT_DOWNLOAD),
    ("VideoNotUpload", SPEC_VIDEO_NOT_UPLOAD),
    ("VideoConfigureError", SPEC_VIDEO_CONFIGURE_ERROR),
    ("VideoConfigureStoryError", SPEC_VIDEO_CONFIGURE_STORY_ERROR),
    ("VideoTooLongException", SPEC_VIDEO_TOO_LONG_EXCEPTION),
    ("IGTVNotUpload", SPEC_IGTV_NOT_UPLOAD),
    ("IGTVConfigureError", SPEC_IGTV_CONFIGURE_ERROR),
    ("ClipNotUpload", SPEC_CLIP_NOT_UPLOAD),
    ("ClipConfigureError", SPEC_CLIP_CONFIGURE_ERROR),
    ("AlbumNotDownload", SPEC_ALBUM_NOT_DOWNLOAD),
    ("AlbumUnknownFormat", SPEC_ALBUM_UNKNOWN_FORMAT),
    ("AlbumConfigureError", SPEC_ALBUM_CONFIGURE_ERROR),
    ("StoryNotFound", SPEC_STORY_NOT_FOUND),
    ("HighlightNotFound", SPEC_HIGHLIGHT_NOT_FOUND),
    ("HashtagError", SPEC_HASHTAG_ERROR),
    ("HashtagNotFound", SPEC_HASHTAG_NOT_FOUND),
    ("HashtagPageWarning", SPEC_HASHTAG_PAGE_WARNING),
    ("LocationError", SPEC_LOCATION_ERROR),
    ("LocationNotFound", SPEC_LOCATION_NOT_FOUND),
    ("CommentNotFound", SPEC_COMMENT_NOT_FOUND),
    ("CommentsDisabled", SPEC_COMMENTS_DISABLED),
    ("ShareDecodeError", SPEC_SHARE_DECODE_ERROR),
    ("NoteNotFound", SPEC_NOTE_NOT_FOUND),
    ("TrackNotFound", SPEC_TRACK_NOT_FOUND),
)


for exception_name, spec in REGISTRATION_SPECS:
    _register_exception(exception_name, spec)


REGISTERED_EXCEPTION_NAMES = frozenset(_REGISTERED_EXCEPTION_NAMES)
"""Exception names intentionally registered in this module."""
